### ISSUE TITLE
Rename to liftbridge-api perhaps?

### ISSUE THREAD

**Issue by llchan** [liftbridge-io/liftbridge-api#7]
There are non-gRPC things that we should spec out here:
- NATS message envelope header
- The message encoding which doesn't necessarily need to flow through gRPC
- Maybe in the future, we might spec out a formal on-disk format. Since we're dealing with (I think) log-structured storage, we should be able to get direct replay capabilities to e.g. ingest batches and dump them into a db or something.

Since the scope extends beyond the gRPC interface, should we rename this to liftbridge-api?  I don't feel _super_ strongly about this, just a thought.

**Comment by tylertreat** [comment]
Renamed
